name: marco_bavagnoli_web
description: I'm Marco Bavagnoli, an Italian software developer

publish_to: 'Besimsoft'

version: 1.0.2+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_analytics: ^9.1.8
  ionicons: ^0.1.2
  easy_localization: ^3.0.1
  url_strategy: ^0.2.0
  auto_animated: ^3.0.1
  google_fonts: ^3.0.0
  firebase_core_web: ^1.6.4
  seo_renderer: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

